name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: |
        touch .env
        echo "${{ secrets.frontendenv }}" > .env

    # 🛠️ Fix directory ownership before build to avoid EACCES
    - name: Fix permissions before build
      run: |
        sudo chown -R $USER:$USER .
        sudo chmod -R u+rwX,go+rX .

    - name: Build React frontend
      run: npm run build

    - name: Serve React build with PM2
      run: |
        pm2 delete AdminFrontendServer || true
        pm2 serve build --name AdminFrontendServer --watch
        pm2 save
